// This file contains the configuration for all sites
export type SiteType = {
  id: string
  name: string
  ipAddress: string // Added IP address for connectivity check
  cameras: CameraConfig[] // Added cameras configuration
  currentTopics: string[]
  subTopics: string[]
  voltageTopics: string[]
  networkTopics: string[]
  voltageSubTopics: string[]
  powerTopics: string[]
  powerSubTopics: string[]
  neutralTopics: string[]
  subNeutralTopics: string[]
  tempTopics: string[]
  humTopics: string[]
  waterTopics: string[]
  airflowTopics: string[]
  selectedTimeStamp: string
  status?: "active" | "inactive" | "development"
}

export type CameraConfig = {
  id: string
  name: string
  ipAddress: string
  type: "indoor" | "outdoor" | "ptz"
  location: string
  status?: "online" | "offline" | "unknown"
}

// Site configurations
export const sitesConfig: Record<string, SiteType> = {
  "F21: Al Faqah": {
    id: "f21",
    name: "F21: Al Faqah",
    ipAddress: "192.168.1.21", // Example IP address
    cameras: [
      { id: "cam1", name: "Main Entrance", ipAddress: "192.168.1.101", type: "outdoor", location: "Front Gate" },
      { id: "cam2", name: "Mining Room", ipAddress: "192.168.1.102", type: "indoor", location: "Mining Area" },
      { id: "cam3", name: "Filter Room", ipAddress: "192.168.1.103", type: "indoor", location: "Filter Area" },
      { id: "cam4", name: "Perimeter", ipAddress: "192.168.1.104", type: "ptz", location: "Boundary Wall" },
    ],
    currentTopics: ["Faqah/a/Current L1", "Faqah/a/Current L2", "Faqah/a/Current L3"],
    subTopics: ["Faqah/Current L1", "Faqah/Current L2", "Faqah/Current L3"],
    voltageTopics: ["Faqah/a/Phase V1", "Faqah/a/Phase V2", "Faqah/a/Phase V3"],
    networkTopics: ["Faqah/Network"],
    voltageSubTopics: ["Faqah/Phase V1", "Faqah/Phase V2", "Faqah/Phase V3"],
    powerTopics: ["Faqah/a/Active Power L1", "Faqah/a/Active Power L2", "Faqah/a/Active Power L3"],
    powerSubTopics: ["Faqah/Active Power L1", "Faqah/Active Power L2", "Faqah/Active Power L3"],
    neutralTopics: [
      "Faqah/a/Neutral V1",
      "Faqah/a/Neutral V2",
      "Faqah/a/Neutral V3",
      "Faqah/a/Total Active Power",
      "Faqah/a/Frequency",
    ],
    subNeutralTopics: [
      "Faqah/Neutral V1",
      "Faqah/Neutral V2",
      "Faqah/Neutral V3",
      "Faqah/Total Active Power",
      "Faqah/Frequency",
    ],
    tempTopics: ["Faqah/FilterRoom/T", "Faqah/MinningRoom/T", "Faqah/RpiRoom/T", "Faqah/ExhuastRoom/T"],
    humTopics: ["Faqah/FilterRoom/H", "Faqah/MinningRoom/H", "Faqah/RpiRoom/H", "Faqah/ExhuastRoom/H"],
    waterTopics: ["Faqah/Water"],
    airflowTopics: ["Faqah/AirflowH"],
    selectedTimeStamp: "Al_Faqaa",
    status: "active",
  },
  "F24: Khaznah": {
    id: "f24",
    name: "F24: Khaznah",
    ipAddress: "192.168.1.24", // Example IP address
    cameras: [
      { id: "cam1", name: "Main Entrance", ipAddress: "192.168.1.201", type: "outdoor", location: "Front Gate" },
      { id: "cam2", name: "Mining Room", ipAddress: "192.168.1.202", type: "indoor", location: "Mining Area" },
      { id: "cam3", name: "Filter Room", ipAddress: "192.168.1.203", type: "indoor", location: "Filter Area" },
    ],
    currentTopics: ["Kasna1/Current L1", "Kasna1/Current L2", "Kasna1/Current L3"],
    subTopics: ["Kasna1/Current L1", "Kasna1/Current L2", "Kasna1/Current L3"],
    voltageTopics: ["Kasna1/Phase V1", "Kasna1/Phase V2", "Kasna1/Phase V3"],
    networkTopics: ["Kasna1/Network"],
    voltageSubTopics: ["Kasna1/Phase V1", "Kasna1/Phase V2", "Kasna1/Phase V3"],
    powerTopics: ["Kasna1/Active Power L1", "Kasna1/Active Power L2", "Kasna1/Active Power L3"],
    powerSubTopics: ["Kasna1/Active Power L1", "Kasna1/Active Power L2", "Kasna1/Active Power L3"],
    neutralTopics: [
      "Kasna1/Neutral V1",
      "Kasna1/Neutral V2",
      "Kasna1/Neutral V3",
      "Kasna1/Total Active Power",
      "Kasna1/Frequency",
    ],
    subNeutralTopics: [
      "Kasna1/Neutral V1",
      "Kasna1/Neutral V2",
      "Kasna1/Neutral V3",
      "Kasna1/Total Active Power",
      "Kasna1/Frequency",
    ],
    tempTopics: ["Kasna1/FilterRoom/T", "Kasna1/MinningRoom/T", "Kasna1/RpiRoom/T", "Kasna1/ExhuastRoom/T"],
    humTopics: ["Kasna1/FilterRoom/H", "Kasna1/MinningRoom/H", "Kasna1/RpiRoom/H", "Kasna1/ExhuastRoom/H"],
    waterTopics: [""],
    airflowTopics: ["Kasna1/AirflowH"],
    selectedTimeStamp: "Kasna",
    status: "active",
  },
  "F22: Forest 1": {
    id: "f22",
    name: "F22: Forest 1",
    currentTopics: ["Forest/a/Current L1", "Forest/a/Current L2", "Forest/a/Current L3"],
    subTopics: ["Forest/Current L1", "Forest/Current L2", "Forest/Current L3"],
    voltageTopics: ["Forest/a/Phase V1", "Forest/a/Phase V2", "Forest/a/Phase V3"],
    networkTopics: ["Forest/Network"],
    voltageSubTopics: ["Forest/Phase V1", "Forest/Phase V2", "Forest/Phase V3"],
    powerTopics: ["Forest/a/Active Power L1", "Forest/a/Active Power L2", "Forest/a/Active Power L3"],
    powerSubTopics: ["Forest/Active Power L1", "Forest/Active Power L2", "Forest/Active Power L3"],
    neutralTopics: [
      "Forest/a/Neutral V1",
      "Forest/a/Neutral V2",
      "Forest/a/Neutral V3",
      "Forest/a/Total Active Power",
      "Forest/a/Frequency",
    ],
    subNeutralTopics: [
      "Forest/Neutral V1",
      "Forest/Neutral V2",
      "Forest/Neutral V3",
      "Forest/Total Active Power",
      "Forest/Frequency",
    ],
    tempTopics: ["Forest/FilterRoom/T", "Forest/MinningRoom/T", "Forest/RpiRoom/T", "Forest/ExhuastRoom/T"],
    humTopics: ["Forest/FilterRoom/H", "Forest/MinningRoom/H", "Forest/RpiRoom/H", "Forest/ExhuastRoom/H"],
    waterTopics: ["Forest/Water"],
    airflowTopics: ["Forest/AirflowH"],
    selectedTimeStamp: "Forest1",
    status: "active",
  },
  "F08: BK 1": {
    id: "f08",
    name: "F08: BK 1",
    currentTopics: ["BK1/Current L1", "BK1/Current L2", "BK1/Current L3"],
    subTopics: ["BK1/Current L1", "BK1/Current L2", "BK1/Current L3"],
    voltageTopics: ["BK1/Phase V1", "BK1/Phase V2", "BK1/Phase V3"],
    networkTopics: ["BK1/Network"],
    voltageSubTopics: ["BK1/Phase V1", "BK1/Phase V2", "BK1/Phase V3"],
    powerTopics: ["BK1/Active Power L1", "BK1/Active Power L2", "BK1/Active Power L3"],
    powerSubTopics: ["BK1/Active Power L1", "BK1/Active Power L2", "BK1/Active Power L3"],
    neutralTopics: [
      "BK1/Neutral V1",
      "BK1/Neutral V2",
      "BK1/Neutral V3",
      "BK1/Total Active Power",
      "BK1/Current L1",
      "BK1/Current L2",
      "BK1/Current L3",
      "BK1/Frequency",
    ],
    subNeutralTopics: [
      "BK1/Neutral V1",
      "BK1/Neutral V2",
      "BK1/Neutral V3",
      "BK1/Total Active Power",
      "BK1/Current L1",
      "BK1/Current L2",
      "BK1/Current L3",
      "BK1/Frequency",
    ],
    tempTopics: ["BK1/FilterRoom/T", "BK1/MinningRoom/T", "BK1/RpiRoom/T", "BK1/ExhuastRoom/T"],
    humTopics: ["BK1/FilterRoom/H", "BK1/MinningRoom/H", "BK1/RpiRoom/H", "BK1/ExhuastRoom/H"],
    waterTopics: ["BK1/Water"],
    airflowTopics: ["BK1/AirflowH"],
    selectedTimeStamp: "BK1",
    status: "active",
  },
  "F09: Liwa 2": {
    id: "f09",
    name: "F09: Liwa 2",
    currentTopics: ["Liwa2/Current L1", "Liwa2/Current L2", "Liwa2/Current L3"],
    subTopics: ["Liwa2/Current L1", "Liwa2/Current L2", "Liwa2/Current L3"],
    voltageTopics: ["Liwa2/Phase V1", "Liwa2/Phase V2", "Liwa2/Phase V3"],
    networkTopics: ["Liwa2/Network"],
    voltageSubTopics: ["Liwa2/Phase V1", "Liwa2/Phase V2", "Liwa2/Phase V3"],
    powerTopics: ["Liwa2/Active Power L1", "Liwa2/Active Power L2", "Liwa2/Active Power L3"],
    powerSubTopics: ["Liwa2/Active Power L1", "Liwa2/Active Power L2", "Liwa2/Active Power L3"],
    neutralTopics: [
      "Liwa2/Neutral V1",
      "Liwa2/Neutral V2",
      "Liwa2/Neutral V3",
      "Liwa2/Total Active Power",
      "Liwa2/Frequency",
    ],
    subNeutralTopics: [
      "Liwa2/Neutral V1",
      "Liwa2/Neutral V2",
      "Liwa2/Neutral V3",
      "Liwa2/Total Active Power",
      "Liwa2/Frequency",
    ],
    tempTopics: ["Liwa2/FilterRoom/T", "Liwa2/MinningRoom/T", "Liwa2/RpiRoom/T", "Liwa2/ExhuastRoom/T"],
    humTopics: ["Liwa2/FilterRoom/H", "Liwa2/MinningRoom/H", "Liwa2/RpiRoom/H", "Liwa2/ExhuastRoom/H"],
    waterTopics: ["Liwa2/Water"],
    airflowTopics: ["Liwa2/AirflowH"],
    selectedTimeStamp: "Liwa2",
    status: "active",
  },
  "F10: Harz 1": {
    id: "f10",
    name: "F10: Harz 1",
    currentTopics: ["Harz1/Current L1", "Harz1/Current L2", "Harz1/Current L3"],
    subTopics: ["Harz1/Current L1", "Harz1/Current L2", "Harz1/Current L3"],
    voltageTopics: ["Harz1/Phase V1", "Harz1/Phase V2", "Harz1/Phase V3"],
    networkTopics: ["Harz1/Network"],
    voltageSubTopics: ["Harz1/Phase V1", "Harz1/Phase V2", "Harz1/Phase V3"],
    powerTopics: ["Harz1/Active Power L1", "Harz1/Active Power L2", "Harz1/Active Power L3"],
    powerSubTopics: ["Harz1/Active Power L1", "Harz1/Active Power L2", "Harz1/Active Power L3"],
    neutralTopics: [
      "Harz1/Neutral V1",
      "Harz1/Neutral V2",
      "Harz1/Neutral V3",
      "Harz1/Total Active Power",
      "Harz1/Frequency",
    ],
    subNeutralTopics: [
      "Harz1/Neutral V1",
      "Harz1/Neutral V2",
      "Harz1/Neutral V3",
      "Harz1/Total Active Power",
      "Harz1/Frequency",
    ],
    tempTopics: ["Harz1/FilterRoom/T", "Harz1/MinningRoom/T", "Harz1/RpiRoom/T", "Harz1/ExhuastRoom/T"],
    humTopics: ["Harz1/FilterRoom/H", "Harz1/MinningRoom/H", "Harz1/RpiRoom/H", "Harz1/ExhuastRoom/H"],
    waterTopics: ["Harz1/Water"],
    airflowTopics: ["Harz1/AirflowH"],
    selectedTimeStamp: "Harz1",
    status: "development",
  },
  "F11: Harz 2": {
    id: "f11",
    name: "F11: Harz 2",
    currentTopics: ["Harz2/Current L1", "Harz2/Current L2", "Harz2/Current L3"],
    subTopics: ["Harz2/Current L1", "Harz2/Current L2", "Harz2/Current L3"],
    voltageTopics: ["Harz2/Phase V1", "Harz2/Phase V2", "Harz2/Phase V3"],
    networkTopics: ["Harz2/Network"],
    voltageSubTopics: ["Harz2/Phase V1", "Harz2/Phase V2", "Harz2/Phase V3"],
    powerTopics: ["Harz2/Active Power L1", "Harz2/Active Power L2", "Harz2/Active Power L3"],
    powerSubTopics: ["Harz2/Active Power L1", "Harz2/Active Power L2", "Harz2/Active Power L3"],
    neutralTopics: [
      "Harz2/Neutral V1",
      "Harz2/Neutral V2",
      "Harz2/Neutral V3",
      "Harz2/Total Active Power",
      "Harz2/Frequency",
    ],
    subNeutralTopics: [
      "Harz2/Neutral V1",
      "Harz2/Neutral V2",
      "Harz2/Neutral V3",
      "Harz2/Total Active Power",
      "Harz2/Frequency",
    ],
    tempTopics: ["Harz2/FilterRoom/T", "Harz2/MinningRoom/T", "Harz2/RpiRoom/T", "Harz2/ExhuastRoom/T"],
    humTopics: ["Harz2/FilterRoom/H", "Harz2/MinningRoom/H", "Harz2/RpiRoom/H", "Harz2/ExhuastRoom/H"],
    waterTopics: ["Harz2/Water"],
    airflowTopics: ["Harz2/AirflowH"],
    selectedTimeStamp: "Harz2",
    status: "active",
  },
  "F12: Al Hayeer": {
    id: "f12",
    name: "F12: Al Hayeer",
    currentTopics: ["Hayeer/Current L1", "Hayeer/Current L2", "Hayeer/Current L3"],
    subTopics: ["Hayeer/Current L1", "Hayeer/Current L2", "Hayeer/Current L3"],
    voltageTopics: ["Hayeer/Phase V1", "Hayeer/Phase V2", "Hayeer/Phase V3"],
    networkTopics: ["Hayeer/Network"],
    voltageSubTopics: ["Hayeer/Phase V1", "Hayeer/Phase V2", "Hayeer/Phase V3"],
    powerTopics: ["Hayeer/Active Power L1", "Hayeer/Active Power L2", "Hayeer/Active Power L3"],
    powerSubTopics: ["Hayeer/Active Power L1", "Hayeer/Active Power L2", "Hayeer/Active Power L3"],
    neutralTopics: [
      "Hayeer/Neutral V1",
      "Hayeer/Neutral V2",
      "Hayeer/Neutral V3",
      "Hayeer/Total Active Power",
      "Hayeer/Frequency",
    ],
    subNeutralTopics: [
      "Hayeer/Neutral V1",
      "Hayeer/Neutral V2",
      "Hayeer/Neutral V3",
      "Hayeer/Total Active Power",
      "Hayeer/Frequency",
    ],
    tempTopics: ["Hayeer/FilterRoom/T", "Hayeer/MinningRoom/T", "Hayeer/RpiRoom/T", "Hayeer/ExhuastRoom/T"],
    humTopics: ["Hayeer/FilterRoom/H", "Hayeer/MinningRoom/H", "Hayeer/RpiRoom/H", "Hayeer/ExhuastRoom/H"],
    waterTopics: ["Hayeer/Water"],
    airflowTopics: ["Hayeer/AirflowH"],
    selectedTimeStamp: "Hayeer",
    status: "active",
  },
  "F14: Omar 1": {
    id: "f14",
    name: "F14: Omar 1",
    currentTopics: ["Omar/Current L1", "Omar/Current L2", "Omar/Current L3"],
    subTopics: ["Omar/Current L1", "Omar/Current L2", "Omar/Current L3"],
    voltageTopics: ["Omar/Phase V1", "Omar/Phase V2", "Omar/Phase V3"],
    networkTopics: ["Omar/Network"],
    voltageSubTopics: ["Omar/Phase V1", "Omar/Phase V2", "Omar/Phase V3"],
    powerTopics: ["Omar/Active Power L1", "Omar/Active Power L2", "Omar/Active Power L3"],
    powerSubTopics: ["Omar/Active Power L1", "Omar/Active Power L2", "Omar/Active Power L3"],
    neutralTopics: [
      "Omar/Neutral V1",
      "Omar/Neutral V2",
      "Omar/Neutral V3",
      "Omar/Total Active Power",
      "Omar/Frequency",
    ],
    subNeutralTopics: [
      "Omar/Neutral V1",
      "Omar/Neutral V2",
      "Omar/Neutral V3",
      "Omar/Total Active Power",
      "Omar/Frequency",
    ],
    tempTopics: ["Omar/FilterRoom/T", "Omar/MinningRoom/T", "Omar/RpiRoom/T", "Omar/ExhuastRoom/T"],
    humTopics: ["Omar/FilterRoom/H", "Omar/MinningRoom/H", "Omar/RpiRoom/H", "Omar/ExhuastRoom/H"],
    waterTopics: ["Omar/Water"],
    airflowTopics: ["Omar/AirflowH"],
    selectedTimeStamp: "Omar",
    status: "active",
  },
  "F15: Omar 2": {
    id: "f15",
    name: "F15: Omar 2",
    currentTopics: ["Omar2/Current L1", "Omar2/Current L2", "Omar2/Current L3"],
    subTopics: ["Omar2/Current L1", "Omar2/Current L2", "Omar2/Current L3"],
    voltageTopics: ["Omar2/Phase V1", "Omar2/Phase V2", "Omar2/Phase V3"],
    networkTopics: ["Omar2/Network"],
    voltageSubTopics: ["Omar2/Phase V1", "Omar2/Phase V2", "Omar2/Phase V3"],
    powerTopics: ["Omar2/Active Power L1", "Omar2/Active Power L2", "Omar2/Active Power L3"],
    powerSubTopics: ["Omar2/Active Power L1", "Omar2/Active Power L2", "Omar2/Active Power L3"],
    neutralTopics: [
      "Omar2/Neutral V1",
      "Omar2/Neutral V2",
      "Omar2/Neutral V3",
      "Omar2/Total Active Power",
      "Omar2/Frequency",
    ],
    subNeutralTopics: [
      "Omar2/Neutral V1",
      "Omar2/Neutral V2",
      "Omar2/Neutral V3",
      "Omar2/Total Active Power",
      "Omar2/Frequency",
    ],
    tempTopics: ["Omar2/FilterRoom/T", "Omar2/MinningRoom/T", "Omar2/RpiRoom/T", "Omar2/ExhuastRoom/T"],
    humTopics: ["Omar2/FilterRoom/H", "Omar2/MinningRoom/H", "Omar2/RpiRoom/H", "Omar2/ExhuastRoom/H"],
    waterTopics: ["Omar2/Water"],
    airflowTopics: ["Omar2/AirflowH"],
    selectedTimeStamp: "Omar2",
    status: "active",
  },
  "F16: Harz 3": {
    id: "f16",
    name: "F16: Harz 3",
    currentTopics: ["Harz3/Current L1", "Harz3/Current L2", "Harz3/Current L3"],
    subTopics: ["Harz3/Current L1", "Harz3/Current L2", "Harz3/Current L3"],
    voltageTopics: ["Harz3/Phase V1", "Harz3/Phase V2", "Harz3/Phase V3"],
    networkTopics: ["Harz3/Network"],
    voltageSubTopics: ["Harz3/Phase V1", "Harz3/Phase V2", "Harz3/Phase V3"],
    powerTopics: ["Harz3/Active Power L1", "Harz3/Active Power L2", "Harz3/Active Power L3"],
    powerSubTopics: ["Harz3/Active Power L1", "Harz3/Active Power L2", "Harz3/Active Power L3"],
    neutralTopics: [
      "Harz3/Neutral V1",
      "Harz3/Neutral V2",
      "Harz3/Neutral V3",
      "Harz3/Total Active Power",
      "Harz3/Frequency",
    ],
    subNeutralTopics: [
      "Harz3/Neutral V1",
      "Harz3/Neutral V2",
      "Harz3/Neutral V3",
      "Harz3/Total Active Power",
      "Harz3/Frequency",
    ],
    tempTopics: ["Harz3/FilterRoom/T", "Harz3/MinningRoom/T", "Harz3/RpiRoom/T", "Harz3/ExhuastRoom/T"],
    humTopics: ["Harz3/FilterRoom/H", "Harz3/MinningRoom/H", "Harz3/RpiRoom/H", "Harz3/ExhuastRoom/H"],
    waterTopics: ["Harz3/Water"],
    airflowTopics: ["Harz3/AirflowH"],
    selectedTimeStamp: "Harz3",
    status: "active",
  },
  "F17: BK 2": {
    id: "f17",
    name: "F17: BK 2",
    currentTopics: ["BK2/Current L1", "BK2/Current L2", "BK2/Current L3"],
    subTopics: ["BK2/Current L1", "BK2/Current L2", "BK2/Current L3"],
    voltageTopics: ["BK2/Phase V1", "BK2/Phase V2", "BK2/Phase V3"],
    networkTopics: ["BK2/Network"],
    voltageSubTopics: ["BK2/Phase V1", "BK2/Phase V2", "BK2/Phase V3"],
    powerTopics: ["BK2/Active Power L1", "BK2/Active Power L2", "BK2/Active Power L3"],
    powerSubTopics: ["BK2/Active Power L1", "BK2/Active Power L2", "BK2/Active Power L3"],
    neutralTopics: ["BK2/Neutral V1", "BK2/Neutral V2", "BK2/Neutral V3", "BK2/Total Active Power", "BK2/Frequency"],
    subNeutralTopics: ["BK2/Neutral V1", "BK2/Neutral V2", "BK2/Neutral V3", "BK2/Total Active Power", "BK2/Frequency"],
    tempTopics: ["BK2/FilterRoom/T", "BK2/MinningRoom/T", "BK2/RpiRoom/T", "BK2/ExhuastRoom/T"],
    humTopics: ["BK2/FilterRoom/H", "BK2/MinningRoom/H", "BK2/RpiRoom/H", "BK2/ExhuastRoom/H"],
    waterTopics: ["BK2/Water"],
    airflowTopics: ["BK2/AirflowH"],
    selectedTimeStamp: "BK2",
    status: "active",
  },
  "F18: BK 3": {
    id: "f18",
    name: "F18: BK 3",
    currentTopics: ["BK3/Current L1", "BK3/Current L2", "BK3/Current L3"],
    subTopics: ["BK3/Current L1", "BK3/Current L2", "BK3/Current L3"],
    voltageTopics: ["BK3/Phase V1", "BK3/Phase V2", "BK3/Phase V3"],
    networkTopics: ["BK3/Network"],
    voltageSubTopics: ["BK3/Phase V1", "BK3/Phase V2", "BK3/Phase V3"],
    powerTopics: ["BK3/Active Power L1", "BK3/Active Power L2", "BK3/Active Power L3"],
    powerSubTopics: ["BK3/Active Power L1", "BK3/Active Power L2", "BK3/Active Power L3"],
    neutralTopics: ["BK3/Neutral V1", "BK3/Neutral V2", "BK3/Neutral V3", "BK3/Total Active Power", "BK3/Frequency"],
    subNeutralTopics: ["BK3/Neutral V1", "BK3/Neutral V2", "BK3/Neutral V3", "BK3/Total Active Power", "BK3/Frequency"],
    tempTopics: ["BK3/FilterRoom/T", "BK3/MinningRoom/T", "BK3/RpiRoom/T", "BK3/ExhuastRoom/T"],
    humTopics: ["BK3/FilterRoom/H", "BK3/MinningRoom/H", "BK3/RpiRoom/H", "BK3/ExhuastRoom/H"],
    waterTopics: ["BK3/Water"],
    airflowTopics: ["BK3/AirflowH"],
    selectedTimeStamp: "BK3",
    status: "development",
  },
  "F19: Wagan 1": {
    id: "f19",
    name: "F19: Wagan 1",
    currentTopics: ["Wagan/Current L1", "Wagan/Current L2", "Wagan/Current L3"],
    subTopics: ["Wagan/Current L1", "Wagan/Current L2", "Wagan/Current L3"],
    voltageTopics: ["Wagan/Phase V1", "Wagan/Phase V2", "Wagan/Phase V3"],
    networkTopics: ["Wagan/Network"],
    voltageSubTopics: ["Wagan/Phase V1", "Wagan/Phase V2", "Wagan/Phase V3"],
    powerTopics: ["Wagan/Active Power L1", "Wagan/Active Power L2", "Wagan/Active Power L3"],
    powerSubTopics: ["Wagan/Active Power L1", "Wagan/Active Power L2", "Wagan/Active Power L3"],
    neutralTopics: [
      "Wagan/Neutral V1",
      "Wagan/Neutral V2",
      "Wagan/Neutral V3",
      "Wagan/Total Active Power",
      "Wagan/Frequency",
    ],
    subNeutralTopics: [
      "Wagan/Neutral V1",
      "Wagan/Neutral V2",
      "Wagan/Neutral V3",
      "Wagan/Total Active Power",
      "Wagan/Frequency",
    ],
    tempTopics: ["Wagan/FilterRoom/T", "Wagan/MinningRoom/T", "Wagan/RpiRoom/T", "Wagan/ExhuastRoom/T"],
    humTopics: ["Wagan/FilterRoom/H", "Wagan/MinningRoom/H", "Wagan/RpiRoom/H", "Wagan/ExhuastRoom/H"],
    waterTopics: ["Wagan/Water"],
    airflowTopics: ["Wagan/AirflowH"],
    selectedTimeStamp: "Wagan",
    status: "active",
  },
  "F20: Mafraq": {
    id: "f20",
    name: "F20: Mafraq",
    currentTopics: ["Mafraq/Current L1", "Mafraq/Current L2", "Mafraq/Current L3"],
    subTopics: ["Mafraq/Current L1", "Mafraq/Current L2", "Mafraq/Current L3"],
    voltageTopics: ["Mafraq/Phase V1", "Mafraq/Phase V2", "Mafraq/Phase V3"],
    networkTopics: ["Mafraq/Network"],
    voltageSubTopics: ["Mafraq/Phase V1", "Mafraq/Phase V2", "Mafraq/Phase V3"],
    powerTopics: ["Mafraq/Active Power L1", "Mafraq/Active Power L2", "Mafraq/Active Power L3"],
    powerSubTopics: ["Mafraq/Active Power L1", "Mafraq/Active Power L2", "Mafraq/Active Power L3"],
    neutralTopics: [
      "Mafraq/Neutral V1",
      "Mafraq/Neutral V2",
      "Mafraq/Neutral V3",
      "Mafraq/Total Active Power",
      "Mafraq/Frequency",
    ],
    subNeutralTopics: [
      "Mafraq/Neutral V1",
      "Mafraq/Neutral V2",
      "Mafraq/Neutral V3",
      "Mafraq/Total Active Power",
      "Mafraq/Frequency",
    ],
    tempTopics: ["Mafraq/FilterRoom/T", "Mafraq/MinningRoom/T", "Mafraq/RpiRoom/T", "Mafraq/ExhuastRoom/T"],
    humTopics: ["Mafraq/FilterRoom/H", "Mafraq/MinningRoom/H", "Mafraq/RpiRoom/H", "Mafraq/ExhuastRoom/H"],
    waterTopics: ["Mafraq/Water"],
    airflowTopics: ["Mafraq/AirflowH"],
    selectedTimeStamp: "Mafraq",
    status: "development",
  },
  "F23: Forest 2": {
    id: "f23",
    name: "F23: Forest 2",
    currentTopics: ["Forest2/Current L1", "Forest2/Current L2", "Forest2/Current L3"],
    subTopics: ["Forest2/Current L1", "Forest2/Current L2", "Forest2/Current L3"],
    voltageTopics: ["Forest2/Phase V1", "Forest2/Phase V2", "Forest2/Phase V3"],
    networkTopics: ["Forest2/Network"],
    voltageSubTopics: ["Forest2/Phase V1", "Forest2/Phase V2", "Forest2/Phase V3"],
    powerTopics: ["Forest2/Active Power L1", "Forest2/Active Power L2", "Forest2/Active Power L3"],
    powerSubTopics: ["Forest2/Active Power L1", "Forest2/Active Power L2", "Forest2/Active Power L3"],
    neutralTopics: [
      "Forest2/Neutral V1",
      "Forest2/Neutral V2",
      "Forest2/Neutral V3",
      "Forest2/Total Active Power",
      "Forest2/Frequency",
    ],
    subNeutralTopics: [
      "Forest2/Neutral V1",
      "Forest2/Neutral V2",
      "Forest2/Neutral V3",
      "Forest2/Total Active Power",
      "Forest2/Frequency",
    ],
    tempTopics: ["Forest2/FilterRoom/T", "Forest2/MinningRoom/T", "Forest2/RpiRoom/T", "Forest2/ExhuastRoom/T"],
    humTopics: ["Forest2/FilterRoom/H", "Forest2/MinningRoom/H", "Forest2/RpiRoom/H", "Forest2/ExhuastRoom/H"],
    waterTopics: ["Forest2/Water"],
    airflowTopics: ["Forest2/AirflowH"],
    selectedTimeStamp: "Forest2",
    status: "development",
  },
  "AMC01: LIWA 3": {
    id: "amc01",
    name: "AMC01: LIWA 3",
    currentTopics: ["Liwa3/Current L1", "Liwa3/Current L2", "Liwa3/Current L3"],
    subTopics: ["Liwa3/Current L1", "Liwa3/Current L2", "Liwa3/Current L3"],
    voltageTopics: ["Liwa3/Phase V1", "Liwa3/Phase V2", "Liwa3/Phase V3"],
    networkTopics: ["Liwa3/Network"],
    voltageSubTopics: ["Liwa3/Phase V1", "Liwa3/Phase V2", "Liwa3/Phase V3"],
    powerTopics: ["Liwa3/Active Power L1", "Liwa3/Active Power L2", "Liwa3/Active Power L3"],
    powerSubTopics: ["Liwa3/Active Power L1", "Liwa3/Active Power L2", "Liwa3/Active Power L3"],
    neutralTopics: [
      "Liwa3/Neutral V1",
      "Liwa3/Neutral V2",
      "Liwa3/Neutral V3",
      "Liwa3/Total Active Power",
      "Liwa3/Frequency",
    ],
    subNeutralTopics: [
      "Liwa3/Neutral V1",
      "Liwa3/Neutral V2",
      "Liwa3/Neutral V3",
      "Liwa3/Total Active Power",
      "Liwa3/Frequency",
    ],
    tempTopics: ["Liwa3/FilterRoom/T", "Liwa3/MinningRoom/T", "Liwa3/RpiRoom/T", "Liwa3/ExhuastRoom/T"],
    humTopics: ["Liwa3/FilterRoom/H", "Liwa3/MinningRoom/H", "Liwa3/RpiRoom/H", "Liwa3/ExhuastRoom/H"],
    waterTopics: ["Liwa3/Water"],
    airflowTopics: ["Liwa3/AirflowH"],
    selectedTimeStamp: "Liwa3",
    status: "development",
  },
  "EX03: Ahmed": {
    id: "ex03",
    name: "EX03: Ahmed",
    currentTopics: ["Ahmed/Current L1", "Ahmed/Current L2", "Ahmed/Current L3"],
    subTopics: ["Ahmed/Current L1", "Ahmed/Current L2", "Ahmed/Current L3"],
    voltageTopics: ["Ahmed/Phase V1", "Ahmed/Phase V2", "Ahmed/Phase V3"],
    networkTopics: ["Ahmed/Network"],
    voltageSubTopics: ["Ahmed/Phase V1", "Ahmed/Phase V2", "Ahmed/Phase V3"],
    powerTopics: ["Ahmed/Active Power L1", "Ahmed/Active Power L2", "Ahmed/Active Power L3"],
    powerSubTopics: ["Ahmed/Active Power L1", "Ahmed/Active Power L2", "Ahmed/Active Power L3"],
    neutralTopics: [
      "Ahmed/Neutral V1",
      "Ahmed/Neutral V2",
      "Ahmed/Neutral V3",
      "Ahmed/Total Active Power",
      "Ahmed/Frequency",
    ],
    subNeutralTopics: [
      "Ahmed/Neutral V1",
      "Ahmed/Neutral V2",
      "Ahmed/Neutral V3",
      "Ahmed/Total Active Power",
      "Ahmed/Frequency",
    ],
    tempTopics: ["Ahmed/FilterRoom/T", "Ahmed/MinningRoom/T", "Ahmed/RpiRoom/T", "Ahmed/ExhuastRoom/T"],
    humTopics: ["Ahmed/FilterRoom/H", "Ahmed/MinningRoom/H", "Ahmed/RpiRoom/H", "Ahmed/ExhuastRoom/H"],
    waterTopics: ["Ahmed/Water"],
    airflowTopics: ["Ahmed/AirflowH"],
    selectedTimeStamp: "Ahmed",
    status: "development",
  },
  "F26: Naheel": {
    id: "f26",
    name: "F26: Naheel",
    currentTopics: ["Naheel/Current L1", "Naheel/Current L2", "Naheel/Current L3"],
    subTopics: ["Naheel/Current L1", "Naheel/Current L2", "Naheel/Current L3"],
    voltageTopics: ["Naheel/Phase V1", "Naheel/Phase V2", "Naheel/Phase V3"],
    networkTopics: ["Naheel/Network"],
    voltageSubTopics: ["Naheel/Phase V1", "Naheel/Phase V2", "Naheel/Phase V3"],
    powerTopics: ["Naheel/Active Power L1", "Naheel/Active Power L2", "Naheel/Active Power L3"],
    powerSubTopics: ["Naheel/Active Power L1", "Naheel/Active Power L2", "Naheel/Active Power L3"],
    neutralTopics: [
      "Naheel/Neutral V1",
      "Naheel/Neutral V2",
      "Naheel/Neutral V3",
      "Naheel/Total Active Power",
      "Naheel/Frequency",
    ],
    subNeutralTopics: [
      "Naheel/Neutral V1",
      "Naheel/Neutral V2",
      "Naheel/Neutral V3",
      "Naheel/Total Active Power",
      "Naheel/Frequency",
    ],
    tempTopics: ["Naheel/FilterRoom/T", "Naheel/MinningRoom/T", "Naheel/RpiRoom/T", "Naheel/ExhuastRoom/T"],
    humTopics: ["Naheel/FilterRoom/H", "Naheel/MinningRoom/H", "Naheel/RpiRoom/H", "Naheel/ExhuastRoom/H"],
    waterTopics: ["Naheel/Water"],
    airflowTopics: ["Naheel/AirflowH"],
    selectedTimeStamp: "Naheel",
    status: "development",
  },
  "F27: Arad 1": {
    id: "f27",
    name: "F27: Arad 1",
    currentTopics: ["Arad/Current L1", "Arad/Current L2", "Arad/Current L3"],
    subTopics: ["Arad/Current L1", "Arad/Current L2", "Arad/Current L3"],
    voltageTopics: ["Arad/Phase V1", "Arad/Phase V2", "Arad/Phase V3"],
    networkTopics: ["Arad/Network"],
    voltageSubTopics: ["Arad/Phase V1", "Arad/Phase V2", "Arad/Phase V3"],
    powerTopics: ["Arad/Active Power L1", "Arad/Active Power L2", "Arad/Active Power L3"],
    powerSubTopics: ["Arad/Active Power L1", "Arad/Active Power L2", "Arad/Active Power L3"],
    neutralTopics: [
      "Arad/Neutral V1",
      "Arad/Neutral V2",
      "Arad/Neutral V3",
      "Arad/Total Active Power",
      "Arad/Frequency",
    ],
    subNeutralTopics: [
      "Arad/Neutral V1",
      "Arad/Neutral V2",
      "Arad/Neutral V3",
      "Arad/Total Active Power",
      "Arad/Frequency",
    ],
    tempTopics: ["Arad/FilterRoom/T", "Arad/MinningRoom/T", "Arad/RpiRoom/T", "Arad/ExhuastRoom/T"],
    humTopics: ["Arad/FilterRoom/H", "Arad/MinningRoom/H", "Arad/RpiRoom/H", "Arad/ExhuastRoom/H"],
    waterTopics: ["Arad/Water"],
    airflowTopics: ["Arad/AirflowH"],
    selectedTimeStamp: "Arad1",
    status: "active",
  },
  "F28: Nazriya villa": {
    id: "f28",
    name: "F28: Nazriya villa",
    currentTopics: ["Nazriya/Current L1", "Nazriya/Current L2", "Nazriya/Current L3"],
    subTopics: ["Nazriya/Current L1", "Nazriya/Current L2", "Nazriya/Current L3"],
    voltageTopics: ["Nazriya/Phase V1", "Nazriya/Phase V2", "Nazriya/Phase V3"],
    networkTopics: ["Nazriya/Network"],
    voltageSubTopics: ["Nazriya/Phase V1", "Nazriya/Phase V2", "Nazriya/Phase V3"],
    powerTopics: ["Nazriya/Active Power L1", "Nazriya/Active Power L2", "Nazriya/Active Power L3"],
    powerSubTopics: ["Nazriya/Active Power L1", "Nazriya/Active Power L2", "Nazriya/Active Power L3"],
    neutralTopics: [
      "Nazriya/Neutral V1",
      "Nazriya/Neutral V2",
      "Nazriya/Neutral V3",
      "Nazriya/Total Active Power",
      "Nazriya/Frequency",
    ],
    subNeutralTopics: [
      "Nazriya/Neutral V1",
      "Nazriya/Neutral V2",
      "Nazriya/Neutral V3",
      "Nazriya/Total Active Power",
      "Nazriya/Frequency",
    ],
    tempTopics: ["Nazriya/FilterRoom/T", "Nazriya/MinningRoom/T", "Nazriya/RpiRoom/T", "Nazriya/ExhuastRoom/T"],
    humTopics: ["Nazriya/FilterRoom/H", "Nazriya/MinningRoom/H", "Nazriya/RpiRoom/H", "Nazriya/ExhuastRoom/H"],
    waterTopics: ["Nazriya/Water"],
    airflowTopics: ["Nazriya/AirflowH"],
    selectedTimeStamp: "Nazriya",
    status: "development",
  },
  "F29: Zakir": {
    id: "f29",
    name: "F29: Zakir",
    currentTopics: ["Zakir/Current L1", "Zakir/Current L2", "Zakir/Current L3"],
    subTopics: ["Zakir/Current L1", "Zakir/Current L2", "Zakir/Current L3"],
    voltageTopics: ["Zakir/Phase V1", "Zakir/Phase V2", "Zakir/Phase V3"],
    networkTopics: ["Zakir/Network"],
    voltageSubTopics: ["Zakir/Phase V1", "Zakir/Phase V2", "Zakir/Phase V3"],
    powerTopics: ["Zakir/Active Power L1", "Zakir/Active Power L2", "Zakir/Active Power L3"],
    powerSubTopics: ["Zakir/Active Power L1", "Zakir/Active Power L2", "Zakir/Active Power L3"],
    neutralTopics: [
      "Zakir/Neutral V1",
      "Zakir/Neutral V2",
      "Zakir/Neutral V3",
      "Zakir/Total Active Power",
      "Zakir/Frequency",
    ],
    subNeutralTopics: [
      "Zakir/Neutral V1",
      "Zakir/Neutral V2",
      "Zakir/Neutral V3",
      "Zakir/Total Active Power",
      "Zakir/Frequency",
    ],
    tempTopics: ["Zakir/FilterRoom/T", "Zakir/MinningRoom/T", "Zakir/RpiRoom/T", "Zakir/ExhuastRoom/T"],
    humTopics: ["Zakir/FilterRoom/H", "Zakir/MinningRoom/H", "Zakir/RpiRoom/H", "Zakir/ExhuastRoom/H"],
    waterTopics: ["Zakir/Water"],
    airflowTopics: ["Zakir/AirflowH"],
    selectedTimeStamp: "Zakir",
    status: "active",
  },
  "F30: BK 4": {
    id: "f30",
    name: "F30: BK 4",
    currentTopics: ["BK4/Current L1", "BK4/Current L2", "BK4/Current L3"],
    subTopics: ["BK4/Current L1", "BK4/Current L2", "BK4/Current L3"],
    voltageTopics: ["BK4/Phase V1", "BK4/Phase V2", "BK4/Phase V3"],
    networkTopics: ["BK4/Network"],
    voltageSubTopics: ["BK4/Phase V1", "BK4/Phase V2", "BK4/Phase V3"],
    powerTopics: ["BK4/Active Power L1", "BK4/Active Power L2", "BK4/Active Power L3"],
    powerSubTopics: ["BK4/Active Power L1", "BK4/Active Power L2", "BK4/Active Power L3"],
    neutralTopics: ["BK4/Neutral V1", "BK4/Neutral V2", "BK4/Neutral V3", "BK4/Total Active Power", "BK4/Frequency"],
    subNeutralTopics: ["BK4/Neutral V1", "BK4/Neutral V2", "BK4/Neutral V3", "BK4/Total Active Power", "BK4/Frequency"],
    tempTopics: ["BK4/FilterRoom/T", "BK4/MinningRoom/T", "BK4/RpiRoom/T", "BK4/ExhuastRoom/T"],
    humTopics: ["BK4/FilterRoom/H", "BK4/MinningRoom/H", "BK4/RpiRoom/H", "BK4/ExhuastRoom/H"],
    waterTopics: ["BK4/Water"],
    airflowTopics: ["BK4/AirflowH"],
    selectedTimeStamp: "BK4",
    status: "active",
  },
  "F31: Naheel 2": {
    id: "f31",
    name: "F31: Naheel 2",
    currentTopics: ["Naheel2/Current L1", "Naheel2/Current L2", "Naheel2/Current L3"],
    subTopics: ["Naheel2/Current L1", "Naheel2/Current L2", "Naheel2/Current L3"],
    voltageTopics: ["Naheel2/Phase V1", "Naheel2/Phase V2", "Naheel2/Phase V3"],
    networkTopics: ["Naheel2/Network"],
    voltageSubTopics: ["Naheel2/Phase V1", "Naheel2/Phase V2", "Naheel2/Phase V3"],
    powerTopics: ["Naheel2/Active Power L1", "Naheel2/Active Power L2", "Naheel2/Active Power L3"],
    powerSubTopics: ["Naheel2/Active Power L1", "Naheel2/Active Power L2", "Naheel2/Active Power L3"],
    neutralTopics: [
      "Naheel2/Neutral V1",
      "Naheel2/Neutral V2",
      "Naheel2/Neutral V3",
      "Naheel2/Total Active Power",
      "Naheel2/Frequency",
    ],
    subNeutralTopics: [
      "Naheel2/Neutral V1",
      "Naheel2/Neutral V2",
      "Naheel2/Neutral V3",
      "Naheel2/Total Active Power",
      "Naheel2/Frequency",
    ],
    tempTopics: ["Naheel2/FilterRoom/T", "Naheel2/MinningRoom/T", "Naheel2/RpiRoom/T", "Naheel2/ExhuastRoom/T"],
    humTopics: ["Naheel2/FilterRoom/H", "Naheel2/MinningRoom/H", "Naheel2/RpiRoom/H", "Naheel2/ExhuastRoom/H"],
    waterTopics: ["Naheel2/Water"],
    airflowTopics: ["Naheel2/AirflowH"],
    selectedTimeStamp: "Naheel2",
    status: "development",
  },
  "F32: Wagan 3": {
    id: "f32",
    name: "F32: Wagan 3",
    currentTopics: ["Wagan3/Current L1", "Wagan3/Current L2", "Wagan3/Current L3"],
    subTopics: ["Wagan3/Current L1", "Wagan3/Current L2", "Wagan3/Current L3"],
    voltageTopics: ["Wagan3/Phase V1", "Wagan3/Phase V2", "Wagan3/Phase V3"],
    networkTopics: ["Wagan3/Network"],
    voltageSubTopics: ["Wagan3/Phase V1", "Wagan3/Phase V2", "Wagan3/Phase V3"],
    powerTopics: ["Wagan3/Active Power L1", "Wagan3/Active Power L2", "Wagan3/Active Power L3"],
    powerSubTopics: ["Wagan3/Active Power L1", "Wagan3/Active Power L2", "Wagan3/Active Power L3"],
    neutralTopics: [
      "Wagan3/Neutral V1",
      "Wagan3/Neutral V2",
      "Wagan3/Neutral V3",
      "Wagan3/Total Active Power",
      "Wagan3/Frequency",
    ],
    subNeutralTopics: [
      "Wagan3/Neutral V1",
      "Wagan3/Neutral V2",
      "Wagan3/Neutral V3",
      "Wagan3/Total Active Power",
      "Wagan3/Frequency",
    ],
    tempTopics: ["Wagan3/FilterRoom/T", "Wagan3/MinningRoom/T", "Wagan3/RpiRoom/T", "Wagan3/ExhuastRoom/T"],
    humTopics: ["Wagan3/FilterRoom/H", "Wagan3/MinningRoom/H", "Wagan3/RpiRoom/H", "Wagan3/ExhuastRoom/H"],
    waterTopics: ["Wagan3/Water"],
    airflowTopics: ["Wagan3/AirflowH"],
    selectedTimeStamp: "Wagan3",
    status: "development",
  },
  "F33: Wagan 4": {
    id: "f33",
    name: "F33: Wagan 4",
    currentTopics: ["Wagan4/Current L1", "Wagan4/Current L2", "Wagan4/Current L3"],
    subTopics: ["Wagan4/Current L1", "Wagan4/Current L2", "Wagan4/Current L3"],
    voltageTopics: ["Wagan4/Phase V1", "Wagan4/Phase V2", "Wagan4/Phase V3"],
    networkTopics: ["Wagan4/Network"],
    voltageSubTopics: ["Wagan4/Phase V1", "Wagan4/Phase V2", "Wagan4/Phase V3"],
    powerTopics: ["Wagan4/Active Power L1", "Wagan4/Active Power L2", "Wagan4/Active Power L3"],
    powerSubTopics: ["Wagan4/Active Power L1", "Wagan4/Active Power L2", "Wagan4/Active Power L3"],
    neutralTopics: [
      "Wagan4/Neutral V1",
      "Wagan4/Neutral V2",
      "Wagan4/Neutral V3",
      "Wagan4/Total Active Power",
      "Wagan4/Frequency",
    ],
    subNeutralTopics: [
      "Wagan4/Neutral V1",
      "Wagan4/Neutral V2",
      "Wagan4/Neutral V3",
      "Wagan4/Total Active Power",
      "Wagan4/Frequency",
    ],
    tempTopics: ["Wagan4/FilterRoom/T", "Wagan4/MinningRoom/T", "Wagan4/RpiRoom/T", "Wagan4/ExhuastRoom/T"],
    humTopics: ["Wagan4/FilterRoom/H", "Wagan4/MinningRoom/H", "Wagan4/RpiRoom/H", "Wagan4/ExhuastRoom/H"],
    waterTopics: ["Wagan4/Water"],
    airflowTopics: ["Wagan4/AirflowH"],
    selectedTimeStamp: "Wagan4",
    status: "development",
  },
  "F34: Arada 2": {
    id: "f34",
    name: "F34: Arada 2",
    currentTopics: ["Arada2/Current L1", "Arada2/Current L2", "Arada2/Current L3"],
    subTopics: ["Arada2/Current L1", "Arada2/Current L2", "Arada2/Current L3"],
    voltageTopics: ["Arada2/Phase V1", "Arada2/Phase V2", "Arada2/Phase V3"],
    networkTopics: ["Arada2/Network"],
    voltageSubTopics: ["Arada2/Phase V1", "Arada2/Phase V2", "Arada2/Phase V3"],
    powerTopics: ["Arada2/Active Power L1", "Arada2/Active Power L2", "Arada2/Active Power L3"],
    powerSubTopics: ["Arada2/Active Power L1", "Arada2/Active Power L2", "Arada2/Active Power L3"],
    neutralTopics: [
      "Arada2/Neutral V1",
      "Arada2/Neutral V2",
      "Arada2/Neutral V3",
      "Arada2/Total Active Power",
      "Arada2/Frequency",
    ],
    subNeutralTopics: [
      "Arada2/Neutral V1",
      "Arada2/Neutral V2",
      "Arada2/Neutral V3",
      "Arada2/Total Active Power",
      "Arada2/Frequency",
    ],
    tempTopics: ["Arada2/FilterRoom/T", "Arada2/MinningRoom/T", "Arada2/RpiRoom/T", "Arada2/ExhuastRoom/T"],
    humTopics: ["Arada2/FilterRoom/H", "Arada2/MinningRoom/H", "Arada2/RpiRoom/H", "Arada2/ExhuastRoom/H"],
    waterTopics: ["Arada2/Water"],
    airflowTopics: ["Arada2/AirflowH"],
    selectedTimeStamp: "Arada2",
    status: "development",
  },
  "F35: Palace 1": {
    id: "f35",
    name: "F35: Palace 1",
    currentTopics: ["Palace1/Current L1", "Palace1/Current L2", "Palace1/Current L3"],
    subTopics: ["Palace1/Current L1", "Palace1/Current L2", "Palace1/Current L3"],
    voltageTopics: ["Palace1/Phase V1", "Palace1/Phase V2", "Palace1/Phase V3"],
    networkTopics: ["Palace1/Network"],
    voltageSubTopics: ["Palace1/Phase V1", "Palace1/Phase V2", "Palace1/Phase V3"],
    powerTopics: ["Palace1/Active Power L1", "Palace1/Active Power L2", "Palace1/Active Power L3"],
    powerSubTopics: ["Palace1/Active Power L1", "Palace1/Active Power L2", "Palace1/Active Power L3"],
    neutralTopics: [
      "Palace1/Neutral V1",
      "Palace1/Neutral V2",
      "Palace1/Neutral V3",
      "Palace1/Total Active Power",
      "Palace1/Frequency",
    ],
    subNeutralTopics: [
      "Palace1/Neutral V1",
      "Palace1/Neutral V2",
      "Palace1/Neutral V3",
      "Palace1/Total Active Power",
      "Palace1/Frequency",
    ],
    tempTopics: ["Palace1/FilterRoom/T", "Palace1/MinningRoom/T", "Palace1/RpiRoom/T", "Palace1/ExhuastRoom/T"],
    humTopics: ["Palace1/FilterRoom/H", "Palace1/MinningRoom/H", "Palace1/RpiRoom/H", "Palace1/ExhuastRoom/H"],
    waterTopics: ["Palace1/Water"],
    airflowTopics: ["Palace1/AirflowH"],
    selectedTimeStamp: "Palace1",
    status: "development",
  },
  "F36: Palace 2": {
    id: "f36",
    name: "F36: Palace 2",
    currentTopics: ["Palace2/Current L1", "Palace2/Current L2", "Palace2/Current L3"],
    subTopics: ["Palace2/Current L1", "Palace2/Current L2", "Palace2/Current L3"],
    voltageTopics: ["Palace2/Phase V1", "Palace2/Phase V2", "Palace2/Phase V3"],
    networkTopics: ["Palace2/Network"],
    voltageSubTopics: ["Palace2/Phase V1", "Palace2/Phase V2", "Palace2/Phase V3"],
    powerTopics: ["Palace2/Active Power L1", "Palace2/Active Power L2", "Palace2/Active Power L3"],
    powerSubTopics: ["Palace2/Active Power L1", "Palace2/Active Power L2", "Palace2/Active Power L3"],
    neutralTopics: [
      "Palace2/Neutral V1",
      "Palace2/Neutral V2",
      "Palace2/Neutral V3",
      "Palace2/Total Active Power",
      "Palace2/Frequency",
    ],
    subNeutralTopics: [
      "Palace2/Neutral V1",
      "Palace2/Neutral V2",
      "Palace2/Neutral V3",
      "Palace2/Total Active Power",
      "Palace2/Frequency",
    ],
    tempTopics: ["Palace2/FilterRoom/T", "Palace2/MinningRoom/T", "Palace2/RpiRoom/T", "Palace2/ExhuastRoom/T"],
    humTopics: ["Palace2/FilterRoom/H", "Palace2/MinningRoom/H", "Palace2/RpiRoom/H", "Palace2/ExhuastRoom/H"],
    waterTopics: ["Palace2/Water"],
    airflowTopics: ["Palace2/AirflowH"],
    selectedTimeStamp: "Palace2",
    status: "development",
  },
  "F37: Hili 1": {
    id: "f37",
    name: "F37: Hili 1",
    currentTopics: ["Hili1/Current L1", "Hili1/Current L2", "Hili1/Current L3"],
    subTopics: ["Hili1/Current L1", "Hili1/Current L2", "Hili1/Current L3"],
    voltageTopics: ["Hili1/Phase V1", "Hili1/Phase V2", "Hili1/Phase V3"],
    networkTopics: ["Hili1/Network"],
    voltageSubTopics: ["Hili1/Phase V1", "Hili1/Phase V2", "Hili1/Phase V3"],
    powerTopics: ["Hili1/Active Power L1", "Hili1/Active Power L2", "Hili1/Active Power L3"],
    powerSubTopics: ["Hili1/Active Power L1", "Hili1/Active Power L2", "Hili1/Active Power L3"],
    neutralTopics: [
      "Hili1/Neutral V1",
      "Hili1/Neutral V2",
      "Hili1/Neutral V3",
      "Hili1/Total Active Power",
      "Hili1/Frequency",
    ],
    subNeutralTopics: [
      "Hili1/Neutral V1",
      "Hili1/Neutral V2",
      "Hili1/Neutral V3",
      "Hili1/Total Active Power",
      "Hili1/Frequency",
    ],
    tempTopics: ["Hili1/FilterRoom/T", "Hili1/MinningRoom/T", "Hili1/RpiRoom/T", "Hili1/ExhuastRoom/T"],
    humTopics: ["Hili1/FilterRoom/H", "Hili1/MinningRoom/H", "Hili1/RpiRoom/H", "Hili1/ExhuastRoom/H"],
    waterTopics: ["Hili1/Water"],
    airflowTopics: ["Hili1/AirflowH"],
    selectedTimeStamp: "Hili1",
    status: "development",
  },
}

// List of all sites for dropdown
export const sitesList = Object.keys(sitesConfig).map((key) => ({
  id: sitesConfig[key].id,
  name: key,
  status: sitesConfig[key].status || "inactive",
}))

